### ISSUE TITLE
Execute Nopol fails

### ISSUE THREAD

**Issue by FalconLK** [SpoonLabs/nopol#165]
Hi there,

I've got faced an error during the compilation and the error is as follows.

```bash
java.lang.IllegalArgumentException: File does not exist in: '-c'
	at xxl.java.library.FileLibrary.fail(FileLibrary.java:129)
	at xxl.java.library.FileLibrary.openFrom(FileLibrary.java:29)
	at xxl.java.library.FileLibrary.urlFrom(FileLibrary.java:100)
	at xxl.java.library.JavaLibrary.classpathFrom(JavaLibrary.java:84)
	at fr.inria.lille.repair.Main.main(Main.java:37)
```

I have tried:

Specifically, the following throws the error.

```
java -jar nopol.jar \
-s src/main/java/ \
-c target/classes:target/test-classes:/home/<user>/.m2/repository/junit/junit/4.11/junit-4.11.jar:/home/<user>/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar \
-t symbolic_examples.symbolic_example_1.NopolExampleTest \
-p ../nopol/lib/z3/z3_for_linux
```

_Note:_  I changed the user as my user name and the nopol.jar as "nopol-0.0.3-SNAPSHOT-jar-with-dependencies.jar"

**Comment by monperrus** [comment]
did you compile the latest version on your own?

**Comment by FalconLK** [comment]
I just cloned and followed the instruction. I also tested with both Mac and Linux platforms and the errors are the same over here.

**Comment by surli** [comment]
@FalconLK did you compile first the test projects with their tests? 
Something like:
```
cd ../test-projects/
mvn test -DskipTests
```

**Comment by FalconLK** [comment]
@surli It appears that the command ```mvn test -DskipTests``` takes forever at the following step.

```
junit.framework.AssertionFailedError: expected:<-3> but was:<3>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at nopol_examples.nopol_example_6.NopolExampleTest.test6(NopolExampleTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running infinitel_examples.infinitel_example_3.InfinitelExampleTest
```

Should I wait for it to be finished first?

**Comment by surli** [comment]
No, you can kill it: actually that's weird, the test shouldn't be launched at all with the `-DskipTests`...

**Comment by FalconLK** [comment]
Still.. Anybody has any idea to fix the error?

**Comment by surli** [comment]
Now you launched the mvn command you still have an error executing the: 
```
java -jar nopol.jar \
-s src/main/java/ \
-c target/classes:target/test-classes:/home/<user>/.m2/repository/junit/junit/4.11/junit-4.11.jar:/home/<user>/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar \
-t symbolic_examples.symbolic_example_1.NopolExampleTest \
-p ../nopol/lib/z3/z3_for_linux
```

from the test-projects folder?

**Comment by FalconLK** [comment]
The exact command I use is following. 

```
java -jar nopol-0.0.3-SNAPSHOT-jar-with-dependencies.jar -s src/main/java/ -c target/classes:target/test-classes:/home/ubuntu/.m2/repository/junit/junit/4.11/junit-4.11.jar:/home/ubuntu/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar -t symbolic_examples.symbolic_example_1.NopolExampleTest -p ../nopol/lib/z3/z3_for_linux
```

**Comment by surli** [comment]
in which folder did you use the command?

**Comment by FalconLK** [comment]
In _/home/ubuntu/apr-test/nopol/test-projects_

**Comment by surli** [comment]
Indeed the bugs appear when using the already existing JAR from the repository: this JAR should only be used to replicate results of an article.

You need to use the last version of Nopol: in order to do so, go in nopol directory, package it using: `mvn package -DskipTests` and then get the new version of nopol in `target/nopol-0.2-SNAPSHOT-jar-with-dependencies.jar`. 

I just checked and it works fine with this version.

**Comment by FalconLK** [comment]
Oh, I tried with the last version and it worked! Thank you very much @surli ! 

Ah, quick question, I've got the following. 

```
11:07:49.540 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Source files: [src/main/java]
11:07:49.555 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Classpath: [file:/home/ubuntu/apr-test/nopol/test-projects/target/classes/, file:/home/ubuntu/apr-test/nopol/test-projects/target/test-classes/, file:/home/ubuntu/.m2/repository/junit/junit/4.11/junit-4.11.jar, file:/home/ubuntu/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar]
11:07:49.555 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Statement type: CONDITIONAL
11:07:49.555 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Args: [symbolic_examples.symbolic_example_1.NopolExampleTest]
11:07:49.566 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Config: Config{synthesisDepth=3, collectStaticMethods=true, collectStaticFields=false, collectLiterals=false, onlyOneSynthesisResult=true, sortExpressions=true, maxLineInvocationPerTest=250, timeoutMethodInvocation=2000, dataCollectionTimeoutInSecondForSynthesis=900, addWeight=0.19478, subWeight=0.04554, mulWeight=0.0102, divWeight=0.00613, andWeight=0.10597, orWeight=0.05708, eqWeight=0.22798, nEqWeight=0.0, lessEqWeight=0.0255, lessWeight=0.0947, methodCallWeight=0.1, fieldAccessWeight=0.08099, constantWeight=0.14232, variableWeight=0.05195, mode=REPAIR, type=CONDITIONAL, synthesis=SMT, oracle=ANGELIC, solver=Z3, solverPath='../nopol/lib/z3/z3_for_linux', projectSources=[src/main/java], projectClasspath='[Ljava.net.URL;@6adca536', projectTests=[symbolic_examples.symbolic_example_1.NopolExampleTest], complianceLevel=7, outputFolder=., json=false}
11:07:49.567 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Available processors (cores): 1
11:07:49.580 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Free memory: 23 MB
11:07:49.585 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Maximum memory: 483 MB
11:07:49.585 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Total memory available to JVM: 30 MB
11:07:49.586 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Java version: 1.8.0_171
11:07:49.587 [main] INFO  fr.inria.lille.repair.nopol.NoPol - JAVA_HOME: /usr/lib/jvm/java-8-oracle
11:07:49.588 [main] INFO  fr.inria.lille.repair.nopol.NoPol - PATH: /home/ubuntu/bin:/home/ubuntu/.local/bin:/opt/maven/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
11:07:59.619 [pool-1-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - OOPS, no statement at all, no test results
11:07:59.621 [pool-1-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - ----INFORMATION----
11:07:59.710 [pool-1-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb classes : 32
11:07:59.712 [pool-1-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb methods : 54
11:07:59.713 [pool-1-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb Statements Analyzed : 0
11:07:59.719 [pool-1-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb Statements with Angelic Value Found : 0
11:07:59.725 [pool-1-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb inputs in SMT : 0
11:07:59.727 [pool-1-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb SMT level: 0
11:07:59.733 [pool-1-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb variables in SMT : 0
11:07:59.733 [pool-1-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - NoPol Execution time : 10095ms
11:07:59.734 [pool-1-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - 
NO_ANGELIC_VALUE
```

I guess there should've been some something like --Patch Found-- but I don't see it. Is it normal?

**Comment by surli** [comment]
Great! :) I close this ticket for now, don't hesitate to open another one in case of problem.
