### ISSUE TITLE
Problem in Running

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [SpoonLabs/nopol#190]
It is my first time that I want to run Nopol in my dataset. I receive the following error.
It should be noted that the test project works good. Also, I am using Java 8, and nopol-0.2-SNAPSHOT-jar-with-dependencies.jar. Also, the source address is "src/main/java/foo/bug1" and bug1.java is the source code in a bug1 directory. When I use "src/main/java" I get another error.

java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at fr.inria.lille.repair.Main.main(Main.java:106)
Caused by: java.lang.NullPointerException
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.lille.localization.GZoltarFaultLocalizer.run(GZoltarFaultLocalizer.java:163)
	at fr.inria.lille.localization.GZoltarFaultLocalizer.<init>(GZoltarFaultLocalizer.java:94)
	at fr.inria.lille.localization.GZoltarFaultLocalizer.<init>(GZoltarFaultLocalizer.java:68)
	at fr.inria.lille.localization.GZoltarFaultLocalizer.createInstance(GZoltarFaultLocalizer.java:60)
	at fr.inria.lille.repair.nopol.NoPol.createLocalizer(NoPol.java:178)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:130)
	at fr.inria.lille.repair.Main$1.call(Main.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by monperrus** [comment]
have you well compiled the source files before Nopol? and set the classpath with everything?

(-c|--classpath) <classpath>
        Define the classpath of the project separated by a path separator (`:` on Linux).
        Must contain the application binary classes (`target/classes`)
        Must contain the application test classes (`target/test-classes`)
        Must contain the library classes (`lib/junit.jar` for instance)

**Comment by Amirfarhad-Nilizadeh** [comment]
Thank you for your help.
Nopol works well with programs which has one class. But, when I have two classes I get this error. One of the methods in the first class calls a method from the second class. 
Should I consider anything when I have two classes?

**Comment by monperrus** [comment]
This should work with two classes. It is likely a misconfiguration.
