### ISSUE TITLE
log4j:ERROR setFile(null,true) call failed.

### ISSUE THREAD

**Issue by jose** [SpoonLabs/nopol#199]
```
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException:  (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
        at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
        at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
        at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
        at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
        at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
        at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
        at org.apache.log4j.PropertyConfigurator.parseCatsAndRenderers(PropertyConfigurator.java:672)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:516)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.apache.log4j.Logger.getLogger(Logger.java:117)
        at spoon.support.reflect.declaration.CtElementImpl.<clinit>(CtElementImpl.java:73)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at sacha.finder.processor.Processor.process(Processor.java:47)
        at fr.inria.lille.repair.common.finder.TestClassFinderRunner.call(TestClassFinderRunner.java:27)
        at fr.inria.lille.repair.common.finder.TestClassFinderRunner.call(TestClassFinderRunner.java:19)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by monperrus** [comment]
The error is thrown by `Class<?> clazz = Class.forName(className);`, this suggests that you have a classpath misconfiguration.

**Comment by jose** [comment]
> The error is thrown by `Class<?> clazz = Class.forName(className);`, this suggests that you have a classpath misconfiguration.

Very likely yes.  Here's is the classpath I'm currently using
```
# Binary directories of the project
target/classes
target/test-classes

# Project's dependencies collected with `mvn dependency:build-classpath`
/homes/gws/jmcampos/.m2/repository/org/eclipse/jdt/org.eclipse.jdt.core/3.13.102/org.eclipse.jdt.core-3.13.102.jar
/homes/gws/jmcampos/.m2/repository/org/eclipse/platform/org.eclipse.core.resources/3.13.700/org.eclipse.core.resources-3.13.700.jar
/homes/gws/jmcampos/.m2/repository/org/eclipse/platform/org.eclipse.core.expressions/3.6.700/org.eclipse.core.expressions-3.6.700.jar
/homes/gws/jmcampos/.m2/repository/org/eclipse/platform/org.eclipse.core.runtime/3.17.100/org.eclipse.core.runtime-3.17.100.jar
/homes/gws/jmcampos/.m2/repository/org/eclipse/platform/org.eclipse.osgi/3.15.200/org.eclipse.osgi-3.15.200.jar
/homes/gws/jmcampos/.m2/repository/org/eclipse/platform/org.eclipse.equinox.common/3.11.0/org.eclipse.equinox.common-3.11.0.jar
/homes/gws/jmcampos/.m2/repository/org/eclipse/platform/org.eclipse.core.jobs/3.10.700/org.eclipse.core.jobs-3.10.700.jar
/homes/gws/jmcampos/.m2/repository/org/eclipse/platform/org.eclipse.equinox.registry/3.8.700/org.eclipse.equinox.registry-3.8.700.jar
/homes/gws/jmcampos/.m2/repository/org/eclipse/platform/org.eclipse.equinox.preferences/3.7.700/org.eclipse.equinox.preferences-3.7.700.jar
/homes/gws/jmcampos/.m2/repository/org/eclipse/platform/org.eclipse.core.contenttype/3.7.600/org.eclipse.core.contenttype-3.7.600.jar
/homes/gws/jmcampos/.m2/repository/org/eclipse/platform/org.eclipse.equinox.app/1.4.400/org.eclipse.equinox.app-1.4.400.jar
/homes/gws/jmcampos/.m2/repository/org/eclipse/platform/org.eclipse.core.filesystem/1.7.700/org.eclipse.core.filesystem-1.7.700.jar
/homes/gws/jmcampos/.m2/repository/org/eclipse/platform/org.eclipse.text/3.10.100/org.eclipse.text-3.10.100.jar
/homes/gws/jmcampos/.m2/repository/org/eclipse/platform/org.eclipse.core.commands/3.9.700/org.eclipse.core.commands-3.9.700.jar
/homes/gws/jmcampos/.m2/repository/junit/junit/4.12/junit-4.12.jar
/homes/gws/jmcampos/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
/homes/gws/jmcampos/.m2/repository/com/github/stefanbirkner/system-rules/1.9.0/system-rules-1.9.0.jar
/homes/gws/jmcampos/.m2/repository/org/mockito/mockito-all/2.0.2-beta/mockito-all-2.0.2-beta.jar
/homes/gws/jmcampos/.m2/repository/com/martiansoftware/jsap/2.1/jsap-2.1.jar
/homes/gws/jmcampos/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
/homes/gws/jmcampos/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
/homes/gws/jmcampos/.m2/repository/org/apache/maven/maven-model/3.5.0/maven-model-3.5.0.jar
/homes/gws/jmcampos/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.24/plexus-utils-3.0.24.jar
/homes/gws/jmcampos/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
/homes/gws/jmcampos/.m2/repository/org/tukaani/xz/1.8/xz-1.8.jar
/homes/gws/jmcampos/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.5/jackson-databind-2.9.5.jar
/homes/gws/jmcampos/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar
/homes/gws/jmcampos/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.5/jackson-core-2.9.5.jar
/homes/gws/jmcampos/.m2/repository/org/apache/commons/commons-compress/1.18/commons-compress-1.18.jar
/homes/gws/jmcampos/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
/homes/gws/jmcampos/.m2/repository/com/mysema/querydsl/querydsl-core/3.6.9/querydsl-core-3.6.9.jar
/homes/gws/jmcampos/.m2/repository/com/infradna/tool/bridge-method-annotation/1.13/bridge-method-annotation-1.13.jar
/homes/gws/jmcampos/.m2/repository/org/jboss/windup/decompiler/fernflower/fernflower/2.5.0.Final/fernflower-2.5.0.Final.jar
/homes/gws/jmcampos/.m2/repository/org/apache/maven/shared/maven-invoker/3.0.1/maven-invoker-3.0.1.jar
/homes/gws/jmcampos/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar
/homes/gws/jmcampos/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.7.1/plexus-component-annotations-1.7.1.jar
/homes/gws/jmcampos/.m2/repository/org/benf/cfr/0.132.0/cfr-0.132.0.jar

# Nopol
/tmp/INRIA_spoon/nopol/nopol/target/nopol-0.2-SNAPSHOT-jar-with-dependencies.jar
```

Which dependency/dependencies am I missing?


--
Best,
Jose

**Comment by tdurieux** [comment]
It is a strange case, it happens when we are trying to find the test classes in the classloader. 

Are you providing a list of tests to nopol?

**Comment by jose** [comment]
> Are you providing a list of tests to nopol?

No, I'm not.

**Comment by tdurieux** [comment]
would it be possible to have the complete execution log?
Thanks

**Comment by jose** [comment]
> would it be possible to have the complete execution log?

Sure, please find it [here](https://github.com/SpoonLabs/nopol/files/4451610/nopol-issue-200.txt).

**Comment by monperrus** [comment]
This is a bug in the SLF4J/Log4J configuration, see https://github.com/SpoonLabs/astor/issues/226#issuecomment-723402341
