### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jdi/Value

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/nopol#26]
(reported by Ariel, running in SMT mode.

any idea? looks like there is a mix of SMT and Dynamoth.

Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jdi/Value
    at fr.inria.lille.spirals.repair.expression.factory.AccessFactory.literal(AccessFactory.java:25)
    at fr.inria.lille.spirals.repair.synthesizer.collect.spoon.ConstantCollector.process(ConstantCollector.java:78)
    at fr.inria.lille.spirals.repair.synthesizer.collect.spoon.ConstantCollector.process(ConstantCollector.java:18)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:92)
    at spoon.reflect.visitor.CtScanner.visitCtBinaryOperator(CtScanner.java:266)
    at spoon.support.reflect.code.CtBinaryOperatorImpl.accept(CtBinaryOperatorImpl.java:35)
    at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
    at spoon.reflect.visitor.CtScanner.visitCtFor(CtScanner.java:417)
    at spoon.support.reflect.code.CtForImpl.accept(CtForImpl.java:44)
    at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:64)
    at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:273)
    at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:46)
    at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
    at spoon.reflect.visitor.CtScanner.visitCtFor(CtScanner.java:419)
    at spoon.support.reflect.code.CtForImpl.accept(CtForImpl.java:44)
    at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:64)
    at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:273)
    at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:46)
    at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
    at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:508)
    at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:58)
    at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:64)
    at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:309)
    at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
    at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
    at spoon.support.RuntimeProcessingManager.process(RuntimeProcessingManager.java:145)
    at spoon.support.RuntimeProcessingManager.process(RuntimeProcessingManager.java:133)
    at fr.inria.lille.commons.spoon.SpoonedFile.processModelledClasses(SpoonedFile.java:136)
    at fr.inria.lille.commons.spoon.SpoonedFile.process(SpoonedFile.java:128)
    at fr.inria.lille.commons.spoon.SpoonedFile.process(SpoonedFile.java:124)
    at fr.inria.lille.repair.nopol.synth.DefaultSynthesizer.buildPatch(DefaultSynthesizer.java:94)
    at fr.inria.lille.repair.nopol.NoPol.solveWithMultipleBuild(NoPol.java:183)
    at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:117)
    at fr.inria.lille.repair.nopol.NoPolLauncher.launch(NoPolLauncher.java:82)
    at fr.inria.lille.repair.Main.main(Main.java:63)

**Comment by monperrus** [comment]
create two classes out of ConstantCollector 
DefautlConstantCollector pure spoon with no dependency to JDI
and
DynamothConstantCollector with dependency to JDI

**Comment by agodio** [comment]
This exception appears with this arguments (and this [IntroClassJava](https://github.com/Spirals-Team/IntroClassJava) program)

I simplified the relative paths. The same Exception is thrown if I replace -c argument with the output of`mvn dependency:build-classpath` (which actually contains the path to tools.jar) 

java -jar nopol-0.2-SNAPSHOT-jar-with-dependencies.jar \
-s digits/5b504b3547416bfd54f138b3caa529ad72d157744b787e0e6f4745a2ff0fc5cc33bc87904b2d7cda9c7858087b2e04ece46d53fe9edd208f68d30a0ae70f363f/000/src/main/java/ \
-c digits/5b504b3547416bfd54f138b3caa529ad72d157744b787e0e6f4745a2ff0fc5cc33bc87904b2d7cda9c7858087b2e04ece46d53fe9edd208f68d30a0ae70f363f/000/target/classes:digits/5b504b3547416bfd54f138b3caa529ad72d157744b787e0e6f4745a2ff0fc5cc33bc87904b2d7cda9c7858087b2e04ece46d53fe9edd208f68d30a0ae70f363f/000/target/test-classes \
-t introclassJava.digits_5b504b35_000BlackboxTest:introclassJava.digits_5b504b35_000WhiteboxTest \
-p nopol/lib/z3/z3_for_mac \
-e condition
